export const Users = [
  {
    id:1,
    profilePicture: "assets/person/1.jpg",
    username: "Alisha",
  },
  {
    id:2,
    profilePicture: "assets/person/2.jpeg",
    username: "Dhruv",
  },
  {
    id:3,
    profilePicture: "assets/person/3.jpeg",
    username: "Jeevika",
  },
  {
    id:4,
    profilePicture: "assets/person/4.jpeg",
    username: "Ishana",
  },
  {
    id:5,
    profilePicture: "assets/person/5.jpg",
    username: "Dora",
  },
  {
    id:6,
    profilePicture: "assets/person/6.jpeg",
    username: "Alex",
  },
  {
    id:7,
    profilePicture: "assets/person/7.jpeg",
    username: "Mahika",
  },
  {
    id:8,
    profilePicture: "assets/person/8.jpeg",
    username: "Harsh",
  },
  {
    id:9,
    profilePicture: "assets/person/9.jpeg",
    username: "Priyansh",
  },
  {
    id:10,
    profilePicture: "assets/person/10.jpeg",
    username: "Nikhil",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "One World, Many Hearts.",
    photo: "assets/post/1.jpg",
    date: "5 mins ago",
    userId: 1,
    like: 64,
    comment: 11,
  },
  {
    id: 2,
    photo: "assets/post/2.jpg",
    date: "15 mins ago",
    userId: 2,
    like: 9,
    comment: 2,
  },
  {
    id: 3,
    desc: "The future depends on what you do today.",
    photo: "assets/post/3.jpg",
    date: "1 hour ago",
    userId: 3,
    like: 191,
    comment: 39,
  },
  {
    id: 4,
    photo: "assets/post/4.jpg",
    date: "4 hours ago",
    userId: 4,
    like: 27,
    comment: 9,
  },
  {
    id: 5,
    photo: "assets/post/5.jpg",
    date: "5 hours ago",
    userId: 5,
    like: 83,
    comment: 25,
  },
  {
    id: 6,
    photo: "assets/post/6.jpg",
    date: "1 day ago",
    userId: 6,
    like: 144,
    comment: 68,
  },
  {
    id: 7,
    desc: "Cherish smiles, leave no room for regrets and sorrow.",
    photo: "assets/post/7.jpg",
    date: "2 days ago",
    userId: 7,
    like: 72,
    comment: 23,
  },
  {
    id: 8,
    photo: "assets/post/8.jpg",
    date: "3 days ago",
    userId: 8,
    like: 198,
    comment: 38,
  },
  {
    id: 9,
    desc: "Influence the world with your authentic self.",
    photo: "assets/post/9.jpg",
    date: "5 days ago",
    userId: 9,
    like: 54,
    comment: 8,
  },
  {
    id: 10,
    photo: "assets/post/10.jpg",
    date: "1 week ago",
    userId: 10,
    like: 171,
    comment: 89,
  },
];
